[".cache/zsh/plugins/ohmyzsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".cache/zsh/plugins/zsh-defer"]
    type = "archive"
    url = "https://github.com/romkatv/zsh-defer/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/zsh-defer**"]
[".cache/zsh/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/zsh-autosuggestions**"]
[".cache/zsh/completions/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".cache/zsh/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.20.0.tar.gz"
    exact = true
    stripComponents = 1
[".config/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/bin/fzf"]
    type = "archive-file"
    url = "https://github.com/junegunn/fzf/releases/download/v0.66.1/fzf-0.66.1-linux_amd64.tar.gz"
    path = "fzf"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/bin/cht"]
    type = "file"
    url = "https://cheat.sh/:cht.sh"
    executable = true
    refreshPeriod = "168h"
[".local/bin/tldr"]
    type = "archive-file"
    url = "https://github.com/raylee/tldr-sh-client/archive/main.tar.gz"
    path = "tldr"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/bin/tmux-sessionizer"]
    type = "file"
    executable = true
    url = "https://raw.githubusercontent.com/martinpales/tmux-sessionizer/master/tmux-sessionizer"
    refreshPeriod = "168h"
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

# vim: ft=toml sw=4 ts=4 et
