[".cache/zsh/plugins/ohmyzsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".cache/zsh/plugins/zsh-defer"]
    type = "archive"
    url = "https://github.com/romkatv/zsh-defer/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/zsh-defer**"]
[".cache/zsh/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
    include = ["*/zsh-autosuggestions**"]
[".cache/zsh/completions/zsh-completions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-completions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".cache/zsh/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.20.0.tar.gz"
    exact = true
    stripComponents = 1
[".config/tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/bin/bat"]
    type = "archive-file"
    url = "https://github.com/sharkdp/bat/releases/download/v0.26.0/bat-v0.26.0-x86_64-unknown-linux-gnu.tar.gz"
    path = "bat"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/bin/difft"]
    type = "archive-file"
    url = "https://github.com/Wilfred/difftastic/releases/download/0.65.0/difft-x86_64-unknown-linux-gnu.tar.gz"
    path = "difft"
    exact = true
    refreshPeriod = "168h"
[".local/bin/fd"]
    type = "archive-file"
    url = "https://github.com/sharkdp/fd/releases/download/v10.3.0/fd-v10.3.0-x86_64-unknown-linux-gnu.tar.gz"
    path = "fd"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/bin/fzf"]
    type = "archive-file"
    url = "https://github.com/junegunn/fzf/releases/download/v0.66.1/fzf-0.66.1-linux_amd64.tar.gz"
    path = "fzf"
    exact = true
    refreshPeriod = "168h"
[".local/bin/cht"]
    type = "file"
    url = "https://cheat.sh/:cht.sh"
    executable = true
    refreshPeriod = "168h"
[".local/bin/lazygit"]
    type = "archive-file"
    url = "https://github.com/jesseduffield/lazygit/releases/download/v0.56.0/lazygit_0.56.0_linux_x86_64.tar.gz"
    path = "lazygit"
    exact = true
    refreshPeriod = "168h"
[".local/bin/rg"]
    type = "archive-file"
    url = "https://github.com/BurntSushi/ripgrep/releases/download/15.1.0/ripgrep-15.1.0-x86_64-unknown-linux-musl.tar.gz"
    path = "rg"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/bin/tldr"]
    type = "archive-file"
    url = "https://github.com/raylee/tldr-sh-client/archive/main.tar.gz"
    path = "tldr"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".local/bin/tmux-sessionizer"]
    type = "file"
    executable = true
    url = "https://raw.githubusercontent.com/martinpales/tmux-sessionizer/refs/heads/feature/zero-depth/tmux-sessionizer"
    refreshPeriod = "168h"
[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

# vim: ft=toml sw=4 ts=4 et
